import type { Metadata } from "next";
import { Work_Sans, Noto_Sans_Syriac } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

const notoSansSyriac = Noto_Sans_Syriac({
  variable: "--font-noto-sans-syriac",
  subsets: ["syriac"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`${workSans.variable} ${notoSansSyriac.variable} antialiased`}
      >
        <main className="bg-white text-alto-950">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
